services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: test
    depends_on:
      test-postgres:
        condition: service_healthy
    image: ${IMAGE_NAME:?}
    restart: always
    env_file: local.env

  test-postgres:
    container_name: test-postgres
    image: postgres:15
    mem_limit: 128m
    restart: unless-stopped
    ports: [ '${PG_HOST_PORT}:${PG_PORT}' ]
    healthcheck:
      test: pg_isready --username=${PG_USER} --dbname=${PG_DB_NAME}
      interval: 3s
      timeout: 3s
      start_period: 3s
      retries: 10
    volumes:
      - pg_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB_NAME}
volumes:
  pg_volume: